package Exercises_03_for_array;

public class Add {		// 연습문제 12

	public static void main(String[] args) {
		// Generated by SH Lee
		int sum = 0;
		int n;
		for (int i=0; i<args.length; i++) {
			
			try {
				n = Integer.parseInt(args[i]);
				sum = sum + n;
			}				
			catch (NumberFormatException e) {
				continue;
			}
		}
		System.out.println(sum);
	}
}
