package Exercises_03_for_array;

public class Average {		// 연습문제 11

	public static void main(String[] args) {
		// Generated by SH Lee
		int sum = 0;
		int avg = 0;
		
		for (int i=0; i<args.length; i++) {
			int n = Integer.parseInt(args[i]);
			sum = sum + n;			
		}
		
		avg = sum / args.length;
		System.out.println(avg);
	}

}		// review : 입력이 없었을때 예외처리 고려
		// if (args.length == 0)
