package Exercises_03_for_array;

public class Ex_02 {

	public static void main(String[] args) {
		// Generated by SH Lee
		int n[][] = {{1}, {1,2,3}, {1}, {1,2,3,4}, {1,2}};
		
		for (int i=0; i<n.length; i++) {
			for (int j=0; j<n[i].length; j++)
				System.out.print(n[i][j]+"\t");
			System.out.println();
		}
	}
}
