package Exercises_03_for_array;
import java.util.Scanner;

public class Ex_04 {

	public static void main(String[] args) {
		// Generated by SH Lee
		Scanner a = new Scanner(System.in);
		System.out.print("소문자 알파벳 하나를 입력하시오>>");
		
		String alphabet = a.next();		// 소문자 입력 a~z to ascii 97~122
		char c = alphabet.charAt(0);	// str을 char로 변환 (ascii 정수값을 받기위함)
		int ascii = (int) c;			// 입력된 문자를 ascii 값으로 변환
		
		if (ascii<97 || ascii>122) {	// 예외 처리 ** 소문자 a to z가 아닐때
			System.out.println("입력이 잘못되었습니다. 알파벳 소문자 1글자만 입력하세요.");
			a.close();
			return;
		}
		
		if (alphabet.length() != 1)	{	// 예외 처리 ** 1글자가 아닐때
			System.out.println("입력이 잘못되었습니다. 알파벳 소문자 1글자만 입력하세요.");
			a.close();
			return;
		}
		
		for (int i=ascii; i>96; i--) {
			for (int j=97; j<i+1; j++) {
				System.out.print((char)j); 
			}
			System.out.println();			
		}
		a.close();		
	}

}		// review - int 값 변수 ascii 이외에도 char 값으로 for 사용할 수 있음.
