package Exercises_03_for_array;
import java.util.Scanner;

public class Ex_06 {

	public static void main(String[] args) {
		// Generated by SH Lee
		Scanner a = new Scanner(System.in);
		int unit[] = {50000, 10000, 1000, 500, 100, 50, 10, 1};
		
		System.out.print("금액을 입력하시오>>");
		int krw = a.nextInt();
		int num = 0;
//		int chg = 0;
		
		for (int i=0; i<unit.length; i++) {
			num = krw / unit[i];
			krw = krw % unit[i];  									// 남은 돈

			if (num==0)
				continue;			
			System.out.println(unit[i] + "원 짜리 : " +num+ "개");
		}
		a.close();
	}

}		// num>0 일때만 출력하는게 좀 더 좋을듯?
