package Exercises_03_for_array;
import java.util.Scanner;

public class Ex_05 {

	public static void main(String[] args) {
		// Generated by SH Lee
		Scanner a = new Scanner(System.in);
		int num[] = new int [10];
		
		System.out.print("양의 정수 10개를 입력하시오>>");
		for (int i=0; i<num.length; i++) {			// 배열 입력
			num[i] = a.nextInt();
		}
		
		System.out.print("3의 배수는 ");
		for (int j=0; j<num.length; j++) {
			if ((num[j]%3) == 0) 
				System.out.print(num[j]+" ");
		}
		
		a.close();
	}

}
