package Exercises_03_for_array;
import java.util.Scanner;

public class Ex_03 {

	public static void main(String[] args) {
		// Generated by SH Lee
		Scanner a = new Scanner(System.in);
		System.out.print("정수를 입력하시오>>");
		int k = a.nextInt();
		
		if (k <= 0) {	// 예외 처리
			System.out.println("0보다 큰 정수를 입력해야 합니다.");
			a.close();
			return;
		}			

		
		for (int i=k; i>0; i--) {
			for (int j=0; j<i; j++) {
				System.out.print("*");
			}
			System.out.println();			
		}
		a.close();		
	}

}	// review - 0 이하의 수에 대한 예외처리 요구
	// 예외처리 적용 완료
