package Exercises_03_for_array;

public class Ex_07 {

	public static void main(String[] args) {
		// Generated by SH Lee
		int rArray[] = new int[10];
		int sum = 0;
		
		System.out.print("랜덤한 정수들 : ");
		
		for (int i=0; i<rArray.length; i++) {
			rArray[i] = (int)(Math.random()*10 + 1);
			sum = sum + rArray[i];
			System.out.print(rArray[i]+ " ");
		}
		
		float avg = (float) sum / rArray.length;
		System.out.println();
		System.out.print("평균은 " +avg);
	}

}
