package Exercises_03_for_array;

public class Ex_09 {

	public static void main(String[] args) {
		// Generated by SH Lee
		int rInt[][] = new int[4][4];
		
		for (int i=0; i<rInt.length; i++) {
			for (int j=0; j<rInt[i].length; j++) {
				rInt[i][j] = (int)(Math.random()*10 + 1);
				System.out.print(rInt[i][j] + "\t");
			}
			System.out.println();
		}
	}
}		// review - 용도에 따라 값넣기, 사용하기를 2중 for문 2부분으로 분리하여 작성할 수 있다.
