package Exercises_03_for_array;
import java.util.Scanner;

public class Ex_15_Multiply {

	public static void main(String[] args) {
		// Generated by SH Lee
		
		int i_num = 0;
		int i_multy = 0;
		
		while (true) {
			
			try {
				Scanner scanner = new Scanner(System.in);
				System.out.print("곱하고자 하는 두 수 입력>>");
				i_num = scanner.nextInt();
				i_multy = scanner.nextInt();
				
				System.out.print(i_num + " x " + i_multy + " = " + i_num*i_multy);
				
				scanner.close();
				break;
			}
			catch (Exception e) {
				System.out.println("정수가 아닙니다. 다시입력하세요.");
				continue;
			}
		}
	}
}		