package Exercises_03_for_array;
import java.util.Scanner;

public class Ex_16 {

	public static void main(String[] args) {
		// Generated by SH Lee
		String str[] = {"가위", "바위", "보"};
		int computer;
				
		Scanner in = new Scanner(System.in);
		System.out.println("컴퓨터와 가위 바위 보 게임을 합니다.");
		
		while (true) {
			System.out.print("가위 바위 보!>>");
			String mine = in.next();
			
			// 그만
			if (mine.equals("그만")) {
				System.out.println("게임을 종료합니다...");
				in.close();
				break;
			}
			
			// 올바른 입력일 경우			
			if (mine.equals("가위")) {
				computer = (int)(Math.random()*3); // 컴퓨터의 선택
				System.out.print("사용자 = " +mine+ " , 컴퓨터 = " +str[computer]+ ",");
				
				switch (str[computer]) {
					case "가위":
						System.out.print(" 비겼습니다.");
						break;
					case "바위":
						System.out.print(" 컴퓨터가 이겼습니다.");
						break;
					case "보":
						System.out.print(" 사용자가 이겼습니다.");
						break;
				}
			}
			else if (mine.equals("바위")) {
				computer = (int)(Math.random()*3); // 컴퓨터의 선택
				System.out.print("사용자 = " +mine+ " , 컴퓨터 = " +str[computer]+ ",");
				
				switch (str[computer]) {
					case "가위":
						System.out.print(" 사용자가 이겼습니다.");
						break;
					case "바위":
						System.out.print(" 비겼습니다.");
						break;
					case "보":
						System.out.print(" 컴퓨터가 이겼습니다.");
						break;
				}
			}
			else if (mine.equals("보")) {
				computer = (int)(Math.random()*3); // 컴퓨터의 선택
				System.out.print("사용자 = " +mine+ " , 컴퓨터 = " +str[computer]+ ",");
				
				switch (str[computer]) {
					case "가위":
						System.out.print(" 컴퓨터가 이겼습니다.");
						break;
					case "바위":
						System.out.print(" 사용자가 이겼습니다.");
						break;
					case "보":
						System.out.print(" 비겼습니다.");
						break;
				}
			}
			// 잘못된 입력일 경우
			else {
				System.out.println("입력이 잘못되었습니다.");
			}
			
			System.out.println();
		}
		
	}

}
