package Exercises_03_for_array;

public class Ex_13 {

	public static void main(String[] args) {
		// Generated by SH Lee
		int ten = 0;
		int one = 0;
		int count;
		
		for (int i=1; i<100; i++) {
			count = 0;
			ten = i / 10;		// 십의 자리 수
			one = i % 10; 		// 일의 자리 수
				
			if ((i<10) && (one%3==0))
				count++;
			if ((i>=10) && (ten%3==0))
				count++;
			if ((i>=10) && (one%3==0) && (one!=0))
				count++;
			
			if (count==1)
				System.out.println(i + " 박수 짝");
			if (count==2)
				System.out.println(i + " 박수 짝짝");
		}
	}
}
