package Exercises_03_for_array;
import java.util.Scanner;

public class Ex_14 {

	public static void main(String[] args) {
		// Generated by SH Lee
		String course[] = {"Java", "C++", "HTML5", "컴퓨터 구조", "안드로이드"};
		int score[] = {95, 88, 76, 62, 55};
		
		Scanner input = new Scanner(System.in);
		
		while (true) {
			System.out.print("과목 이름>>");
			String coursein = input.next();
			int count = 0;
			
			// 그만
			if (coursein.equals("그만"))				// '그만' 입력되면 종료.
				break;
			
			// 과목이 없는 경우
			for (int j=0; j<course.length; j++) {	// 입력값이 배열 요소와 같은게 있는지 확인
				if (course[j].equals(coursein))
					count++;
			}
			if (count == 0) {						// 같은게 없다면 loop 처음으로 간다
				System.out.println("없는 과목입니다.");
				continue;
			}
			
			// 과목이 있는 경우
			for (int i=0; i<course.length; i++) {
				if (course[i].equals(coursein))
					System.out.println(course[i] + "의 점수는 " + score[i]);
			}
		}
		input.close();
	}

}
