package java_Exam;

public class exam_05 {

	public static void main(String[] args) {
		// Generated by SH Lee
		 ExamSample es = new ExamSample();
	     es.fn(2, 3);
	}

}
class ExamSample {
    void fn() {
        System.out.println("없음");
    }
    void fn(int i) {
        System.out.println(i);
    }
    void fn(int i, int j) {
        int k = i + j;
        System.out.println(k);
    }
}