package java_Exam;

public class Wrapper {

	String str = "35.9";
	float f = Float.parseFloat(str);
	double d = (float) f;
	
	public void run() {
		System.out.println(str);
		System.out.println(f);
		System.out.println(d);
	}
	
	
	public static void main(String[] args) {
		// Generated by SH Lee
		new Wrapper().run();
		
	}

}
