package Submit;
import java.util.Scanner;

public class Eng2Kor {

	public static void main(String[] args) {
		// Generated by SH Lee
		// 영어와 한글의 짝을 이루는 2개의 배열을 만들고, 사용자로부터 영어 단어를 입력받아 한글을 출력하는 프로그램을 작성하세요.
		// “exit”를 입력하면 프로그램을 종료합니다.
		
		String eng[] = {"student", "love", "java", "happy", "future"};
		String kor[] = {"학생", "사랑", "자바", "행복", "미래"};
		
		Scanner input = new Scanner(System.in);
		
		while (true) {
			System.out.print("영어 단어를 입력하세요. >> ");	// 영단어 입력
			String eng_input = input.next();
			int count = 0;	// 검증용 카운터
			
			// exit to 종료
			if (eng_input.equals("exit")) {				// "exit" 입력되면 종료.
				System.out.println("종료합니다...");
				break;
			}
			
			// 단어가 없는지 검증하는 과정
			for (int i=0; i<eng.length; i++) {	// 입력값이 배열 요소와 같은게 있으면 count++
				if (eng_input.equals(eng[i])) {
					count++;
				}
			}
			
			// 단어가 없는 경우
			if (count == 0) {					// 같은게 없다면(count>=1, 안내 후 loop 처음으로 간다)
				System.out.println("그런 영어 단어가 없습니다.");
				continue;
			}
			
			// 단어가 있는 경우
			for (int i=0; i<eng.length; i++) {
				if (eng_input.equals(eng[i])) {
					System.out.println(kor[i]);
				}
			}
		}
		input.close();		// 스캐너 입력 종료
	}

}
