package Submit;
import java.util.Scanner;

public class Multiple3 {

	public static void main(String[] args) {
		// Generated by SH Lee
		// 정수를 10개 입력받아 배열에 저장한 후, 배열을 검색하여 3의 배수만 골라 출력하는 프로그램을 작성하세요.
		
		// 정수 10개 입력 (배열)
		Scanner a = new Scanner(System.in);
		int num[] = new int [10];
		
		System.out.print("양의 정수 10개를 입력하시오>>");
		for (int i=0; i<num.length; i++) {			// 배열 입력
			num[i] = a.nextInt();
		}
		
//		배열 검증 출력
//		for (int i=0; i<num.length; i++) {
//			System.out.print(num[i]+ " ");
//			System.out.println();
//		}
		
		// 3의 배수 검증 및 출력
		System.out.print("3의 배수는 ");
		for (int j=0; j<num.length; j++) {
			if ((num[j]%3) == 0) 
				System.out.print(num[j]+" ");
		}
		
		a.close();
	}

}
