package java_Ch14_Swing_Advanced;

import javax.swing.*;

public class MenuEx extends JFrame {
	
	public MenuEx() {
		setTitle("Menu 만들기 예제");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		createMenu();		// 메뉴 생성 메소드, 프레임에 삽입
		setSize(250, 200);
		setVisible(true);
	}

	private void createMenu() {
		JMenuBar mb = new JMenuBar();				// 메뉴바 만들기
		JMenu screenMenu = new JMenu("Screen");		  // 메인메뉴 항목 Screen
		
		screenMenu.add(new JMenuItem("Load"));			// Screen 항목의 하위 메뉴
		screenMenu.add(new JMenuItem("Hide"));			// Screen 항목의 하위 메뉴
		screenMenu.add(new JMenuItem("Reshow"));		// Screen 항목의 하위 메뉴
		screenMenu.addSeparator();						// 분리선 삽입
		screenMenu.add(new JMenuItem("Exit"));			// Screen 항목의 하위 메뉴
		
		mb.add(screenMenu);							// 메뉴바에 Screen 항목 달기
		mb.add(new JMenu("Edit"));					// 메뉴바에 항목 달기
		mb.add(new JMenu("Source"));				// 메뉴바에 항목 달기
		mb.add(new JMenu("Project"));				// 메뉴바에 항목 달기
		mb.add(new JMenu("Run"));					// 메뉴바에 항목 달기
		
		setJMenuBar(mb);							// mb로 메뉴바 세팅
	}
	
	
	public static void main(String[] args) {
		// Generated by SH Lee
		new MenuEx();
	}

}
