package java_Ch14_Swing_Advanced;

import javax.swing.*;
import java.awt.event.*;
import java.awt.*;

public class OptionPaneEx extends JFrame {
	
	Container c;
	
	public OptionPaneEx() {
		setTitle("옵션 팬 예제");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		c = getContentPane();
		setSize(500, 200);
		c.add(new MyPanel(), BorderLayout.NORTH);		// 컨테이너c에 마이패널을 북쪽에 넣는다.
		setVisible(true);
	}
	
	class MyPanel extends JPanel{						// 마이패널
		
		private JButton inputBtn = new JButton("Input Name");	// input버튼
		private JTextField tf = new JTextField(10);				// 텍스트필드
		private JButton confirmBtn = new JButton("Confirm");	// confirm버튼
		private JButton messageBtn = new JButton("Message");	// message버튼
		
		public MyPanel() {								// 마이패널 기본메소드
			setBackground(Color.LIGHT_GRAY);
			add(inputBtn);										// 버튼삽입 (3개)
			add(confirmBtn);
			add(messageBtn);
			add(tf);											// 텍스트필드 삽입
			
			inputBtn.addActionListener(new ActionListener() {		// input버튼 액션리스너 옵션팬(팝업) 입력글자를
				public void actionPerformed(ActionEvent e) {		// 텍스트필드에 넣는다.
					String name = JOptionPane.showInputDialog("이름을 입력하세요.");//팝업창 텍스트
					if (name != null)
						tf.setText(name);
				}
			});
			
			confirmBtn.addActionListener(new ActionListener() {		// confirm버튼 액션리스너
				public void actionPerformed(ActionEvent e) {		// yes or no 버튼이 있는 팝업창
					int result = JOptionPane.showConfirmDialog(null, "계속할 것입니까?", "Confirm", JOptionPane.YES_NO_OPTION);
					if (result == JOptionPane.CLOSED_OPTION)
						tf.setText("Just Closed without Selection");
					else if (result == JOptionPane.YES_OPTION)		// yes 클릭시 텍스트필드에 yes 표시
						tf.setText("Yes");
					else
						tf.setText("No");							// no 클릭시 텍스트필드에 no 표시
				}
			});
			
			messageBtn.addActionListener(new ActionListener() {		// message버튼 액션리스너 
				public void actionPerformed(ActionEvent e) {		// 경고 팝업
					JOptionPane.showMessageDialog(null, "조심하세요.", "Message", JOptionPane.ERROR_MESSAGE);
				}
			});
		}
	}
	
	public static void main(String[] args) {
		// Generated by SH Lee
		new OptionPaneEx();
	}

}
