
public class GarbageEx {

	public static void main(String[] args) {
		// Generated by SH Lee
		String a = new String("Good");
		String b = new String("Bad");
		String c = new String("Normal");
		String d, e;
		
		a = null;
		d = c;
		c = null;
	}

}
