package java_Ch05_Inheritance;

public class GoodCalc extends Calculator {

		public int add(int a, int b) {
			return a+b;
		}
		
		public int subtract(int a, int b) {
			return a-b;
		}
		
		public double average(int[] a) {
			double sum = 0;
			for (int i=0; i<a.length; i++) {
				sum = sum + a[i];
			}
			return sum/a.length;
		}

		
	public static void main(String[] args) {
		// Generated by SH Lee

		GoodCalc cal = new GoodCalc();
		
		System.out.println(cal.add(2, 3));
		System.out.println(cal.subtract(2, 3));
		System.out.println(cal.average(new int[] {2,3,4}));
		
	}

}
