package java_Ch05_Inheritance;

public class InheritanceEX {

	public static void main(String[] args) {
		// Generated by SH Lee

		Student s = new Student();
		s.set();
		System.out.println("setWeight()로 입력한 학생의 몸무게는 " +s.getWeight());
	}

}
