package java_Ch05_Inheritance;

public class InterfaceEx {

	public static void main(String[] args) {
		// Generated by SH Lee
		// Ex. 5-8
		
		SamsungPhone phone = new SamsungPhone();
		phone.printLogo();
		phone.sendCall();
		phone.receiveCall();
		phone.flash();
		
	}

}
