package java_Ch05_Inheritance;

public class InterfaceEx9 {

	public static void main(String[] args) {
		// Generated by SH Lee

		SmartPhone phone = new SmartPhone();
		phone.printLogo();
		phone.sendCall();
		phone.play();
		
		System.out.println("3과 5를 더하면 " +phone.calculate(3, 5));
		phone.schedule();
	}

}
