package java_Ch05_Inheritance;

public class Override {

	public static void main(String[] args) {
		// Generated by SH Lee
		// 예제 5-6
		
		Weapon weapon;
		
		weapon = new Weapon();
		System.out.println("기본 무기의 살상 능력은 " +weapon.fire());
		
		weapon = new Cannon();
		System.out.println("대포의 살상 능력은 " +weapon.fire());
	}

}
