package java_Ch05_Inheritance;

public class SuperEx {

	public static void main(String[] args) {
		// Generated by SH Lee

		ColorPoint3 cp = new ColorPoint3(5,6,"blue");
		cp.showColorPoint3();
	}

}
