package java_Ch04_ClassObject_Ex;

public class Ex_05 {

	public static void main(String[] args) {
		// Generated by SH Lee
		//		5. 다음 설명대로 Circle 클래스와 CircleManager 클래스를 완성하라.​
		//		다음 실행 결과와 같이 3개의 Circle 객체 배열을 만들고, 
		//		x, y, radius 값을 읽어 3개의 Circle 객체를 만들고 show()를 이용하여 이들을 모두 출력한다.​
		//		단, 다음 페이지에서 제시하는 클래스를 수정하여 프로그램을 완성하여라.
		
		new CircleManager().run();
	}

}
