package java_Ch04_ClassObject_Ex;

import java.util.Scanner;

public class Ex_02 {

	public static void main(String[] args) {
		// Generated by SH Lee
		// 2. Grade 클래스를 작성해 보자. 3과목의 점수를 입력받아 Grade 객체를 생성하고
		// 성적 평균을 출력하는 main()과 실행 예시는 다음과 같다. 단, 멤버 변수는 반드시 private으로 선언하시오.
		
		Scanner scanner = new Scanner(System.in);

		System.out.print("수학, 과학, 영어 순으로 3개의 점수 입력 >> ");
		int math = scanner.nextInt();
		int science = scanner.nextInt();
		int english = scanner.nextInt();
		
		Grade me = new Grade(math, science, english);
		System.out.println("평균은 " +me.average());
		
		scanner.close();
	}

}
