package java_Ch04_ClassObject_Ex;

public class Ex_06 {

	public static void main(String[] args) {
		// Generated by SH Lee
		// 6. 앞의 5번 문제는 정답이 공개되어 있다. 이 정답을 참고하여 
		// Circle 클래스와 CircleManager 클래스를 수정하여 다음 실행 결과처럼 되게 하라.​
		
		new CircleManager2().run2();
	}

}
