package java_Ch04_ClassObject_Ex;

public class Ex_03 {

	public static void main(String[] args) {
		// Generated by SH Lee
		// 3. 아래 정보를 활용하여, 노래 1 곡을 나타내는 Song 클래스를 작성하라.  
		// 아래와 같이 출력되도록 main()메소드에 테스트 하는 프로그램을 완성하여라.​
		// 필드 4개​
		//  -노래의 제목을 나타내는 title​
		//  -가수를 나타내는 artist​
		//  -노래가 발표된 연도를 나타내는 year​
		//  -국적을 나타내는 country​
		//	생성자 2개​
		//	- 기본 생성자와 매개변수로 모든 필드를 초기화하는 생성자​
		//	메소드 1개​
		//	- 노래 정보를 출력하는 show() 메소드
		
		Song s1 = new Song("Dancing Queen", "ABBA", 1978, "스웨덴");
		s1.show();
	}
}
