package java_Ch04_ClassObject_Ex;

import java.util.Scanner;

public class Ex_11 {

	public static void main(String[] args) {
		// Generated by SH Lee

		int a;
		int b;
		char c;
		Scanner scanner = new Scanner(System.in);
		System.out.print("두 정수와 연산자를 입력하시오>>");
		a = scanner.nextInt();
		b = scanner.nextInt();
		c = scanner.next().charAt(0);
		
		if (c=='+') {
			Add add1 = new Add();
			add1.setValue(a, b);
			System.out.println(add1.calculate());
		}
		else if (c=='-') {
			Sub sub1 = new Sub();
			sub1.setValue(a, b);
			System.out.println(sub1.calculate());
		}
		else if (c=='*') {
			Mul mul1 = new Mul();
			mul1.setValue(a, b);
			System.out.println(mul1.calculate());
		}
		else if (c=='/') {
			Div div1 = new Div();
			div1.setValue(a, b);
			System.out.println(div1.calculate());
		}
		else
			System.out.println("입력이 잘못되었습니다.");
		
		scanner.close();
	}

}
