package java_Ch04_ClassObject_Ex;

public class Ex_12 {

	public static void main(String[] args) {
		// Generated by SH Lee
		
		Reservation reserv1 = new Reservation();
		reserv1.runReserv();
		
	}

}		
