package java_Ch11_Swing;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class ButtonEx extends JFrame {
	
	private Container c;
	
	public ButtonEx() {
		setTitle("이미지 버튼 예제");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		c = getContentPane();
		c.setLayout(new FlowLayout());
		
		ImageIcon normalIcon = new ImageIcon("images/normalicon.gif");
		ImageIcon rolloverIcon = new ImageIcon("images/rollovericon.gif");
		ImageIcon pressedIcon = new ImageIcon("images/pressedicon.gif");
		
		JButton btn = new JButton("call~~", normalIcon);
		btn.setPressedIcon(pressedIcon);
		btn.setRolloverIcon(rolloverIcon);
		
		c.add(btn);
		
		setSize(250, 150);
		setVisible(true);
	}

	public static void main(String[] args) {
		// Generated by SH Lee
		new ButtonEx();
	}

}
