package java_Ch11_Swing;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class ComboActionEx extends JFrame {
	
	private String[] fruits = {"apple", "banana", "kiwi", "mango"};			// 객체배열 선언 & 생성
	private ImageIcon[] images = {	new ImageIcon("images/apple.jpg"),		// 이미지 객체배열 image 선언 & 생성
									new ImageIcon("images/banana.jpg"),
									new ImageIcon("images/kiwi.jpg"),
									new ImageIcon("images/mango.jpg")};
	private JLabel imgLabel = new JLabel(images[0]);					//??? 왜 0번지만? 초기값인듯?
	private JComboBox<String> strCombo = new JComboBox<String>(fruits);
	private Container c;
	
	public ComboActionEx() {
		setTitle("콥보박스 활용 예제");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		c = getContentPane();
		c.setLayout(new FlowLayout());
		
		c.add(strCombo);
		c.add(imgLabel);
		
		// 액션 리스너 삽입
		strCombo.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				JComboBox<String> cb = (JComboBox<String>) e.getSource();
				int index = cb.getSelectedIndex();
				imgLabel.setIcon(images[index]);
			}
		});
		
		setSize(300, 250);
		setVisible(true);
	}
	
		

	public static void main(String[] args) {
		// Generated by SH Lee
		new ComboActionEx();
	}

}
