package java_Ch11_Swing;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class ComboBoxEx extends JFrame {
	
	private String[] fruits = {	"apple", "banana", "kiwi", "mango", "pear",
								"peach", "berry", "strawberry", "blackberry"};
	private String[] names = {"kitae", "jaemoon", "hyosoo", "namyun"};
	
	private Container c;
	
	public ComboBoxEx() {
		setTitle("콤보박스 예제");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		c = getContentPane();
		c.setLayout(new FlowLayout());
		
		JComboBox<String> strCombo = new JComboBox<String>(fruits);	// 배열에서 바로 아이템 공급받음
		c.add(strCombo);
		
		JComboBox<String> nameCombo = new JComboBox<String>();	// 빈 콤보박스 생성
		for (int i=0; i<names.length; i++) {					// addItem 메소드로 아이템 공급받음
			nameCombo.addItem(names[i]);
		}
		c.add(nameCombo);
		
		setSize(300, 300);
		setVisible(true);
	}
	

	public static void main(String[] args) {
		// Generated by SH Lee
		new ComboBoxEx();
	}

}
