package java_Ch11_Swing;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class JComponentEx extends JFrame {
	
	private Container c;
	
	public JComponentEx() {
		super("JComponent의 공통 메소드 예제");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		c = getContentPane();
		c.setLayout(new FlowLayout());
		
		JButton b1 = new JButton("Magenta/Yellow Button");
		JButton b2 = new JButton(" Disable Button ");
		JButton b3 = new JButton("getX(), getY()");
		
		b1.setBackground(Color.YELLOW);		// 배경색
		b1.setForeground(Color.MAGENTA);	// 글자색	
		b1.setFont(new Font("Arial", Font.ITALIC, 20));		// 폰트 설정 Arial, 기울임체, 20
		b2.setEnabled(false);				// 버튼 비활성
		b3.addActionListener(new ActionListener() {			// 3번 버튼에 액션 - 익명리스너 장착
			public void actionPerformed(ActionEvent e) {
				JButton b = (JButton)e.getSource();
				JComponentEx frame = (JComponentEx)b.getTopLevelAncestor();
				frame.setTitle(b.getX()+ ", " +b.getY()); // 타이틀에 버튼 좌표 출력
			}
		});
		
		c.add(b1);
		c.add(b2);
		c.add(b3);
		
		setSize(260, 200);
		setVisible(true);
	}

	public static void main(String[] args) {
		// Generated by SH Lee
		new JComponentEx();
	}

}
