package java_Ch11_Swing;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class LabelEx extends JFrame {
	
	private Container c;
	
	public LabelEx() {
		setTitle("레이블 예제");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		c = getContentPane();
		c.setLayout(new FlowLayout());
		
		JLabel textLabel = new JLabel("사랑합니다.");
		
		ImageIcon beauty = new ImageIcon("images/beauty.jpg");		// 이미지 아이콘 생성 (이미지 객체)
		JLabel imageLabel = new JLabel(beauty);
		
		ImageIcon normalIcon = new ImageIcon("images/normalicon.gif");
		JLabel label = new JLabel("보고싶으면 전화하세요", normalIcon, SwingConstants.CENTER); //  레이블 내에 이미지객체 삽입
		
		c.add(textLabel);
		c.add(imageLabel);
		c.add(label);
		
		setSize(400, 600);
		setVisible(true);
	}

	public static void main(String[] args) {
		// Generated by SH Lee
		new LabelEx();
	}

}
