package java_Ch11_Swing;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class ListEx extends JFrame {
	
	private String[] fruits = {	"apple", "banana", "kiwi", "mango", "pear",
								"peach", "berry", "strawberry", "blackberry"};
	private ImageIcon[] images = {	new ImageIcon("images/icon1.png"),
									new ImageIcon("images/icon2.png"),
									new ImageIcon("images/icon3.png"),
									new ImageIcon("images/icon4.png")};
	private Container c;
	
	public ListEx() {
		setTitle("리스트 예제");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		c = getContentPane();
		c.setLayout(new FlowLayout());
		
		JList<String> strList = new JList<String>(fruits);		// 배열로 아이템 제공받음
		c.add(strList);
		
		JList<ImageIcon> imageList = new JList<ImageIcon>();	// 빈 컴포넌트 생성 후,
		imageList.setListData(images);							// setListData()로 아이템 제공받음
		c.add(imageList);
		
		JList<String> scrollList = new JList<String>(fruits);
		c.add(new JScrollPane(scrollList));
		
		setSize(300, 300);
		setVisible(true);
	}
	

	public static void main(String[] args) {
		// Generated by SH Lee
		new ListEx();
	}

}
