package java_Ch11_Swing;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class RadioButtonItemEventEx extends JFrame {
	
	private JRadioButton[] radio = new JRadioButton[3];						// 객체배열 radio 선언 & 길이생성
	private String[] text = {"사과", "배", "체리"};
	private ImageIcon[] image = {	new ImageIcon("images/apple.jpg"),		// 이미지 객체배열 image 선언 & 생성
									new ImageIcon("images/pear.jpg"),
									new ImageIcon("images/cherry.jpg")};
	private JLabel imageLabel = new JLabel();
	private Container c;
	
	public RadioButtonItemEventEx() {
		setTitle("라디오버튼 Item Event 예제");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		c = getContentPane();
		c.setLayout(new BorderLayout());
		
		JPanel radioPanel = new JPanel();	// 라디오패널 생성
		radioPanel.setBackground(Color.GRAY);// 라디오패널 배경색
		
		ButtonGroup g = new ButtonGroup();	// 버튼그룸 g 생성
		
		for (int i=0; i<radio.length; i++) {
			radio[i] = new JRadioButton(text[i]);	// 라디오 객체배열 생성
			g.add(radio[i]);						// 버튼그룹에 라디오버튼 추가
			radioPanel.add(radio[i]);				// 라디오패널에 라디오버튼 추가
			radio[i].addItemListener(new MyItemListener());
		}
		
		radio[2].setSelected(true);
		c.add(radioPanel, BorderLayout.NORTH);
		c.add(imageLabel, BorderLayout.CENTER);
		imageLabel.setHorizontalAlignment(SwingConstants.CENTER);
		setSize(300, 200);
		setVisible(true);
	}
	
	class MyItemListener implements ItemListener {
		@Override
		public void itemStateChanged(ItemEvent e) {
			if (e.getStateChange()==ItemEvent.DESELECTED)	// 이건 머지?????????????????????
				return;
			if (radio[0].isSelected())
				imageLabel.setIcon(image[0]);
			else if (radio[1].isSelected())
				imageLabel.setIcon(image[1]);
			else
				imageLabel.setIcon(image[2]);
		}
		
	}

	public static void main(String[] args) {
		// Generated by SH Lee
		new RadioButtonItemEventEx();
	}

}
