package java_Ch11_Swing;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class SliderEx extends JFrame {
	
	private Container c;
	
	public SliderEx() {
		setTitle("슬라이더 예제");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		c = getContentPane();
		c.setLayout(new FlowLayout());
		
		JSlider slider = new JSlider(JSlider.HORIZONTAL, 0, 200, 100);	// min, max, 초기값
		slider.setPaintLabels(true);
		slider.setPaintTicks(true);
		slider.setPaintTrack(true);
		slider.setMajorTickSpacing(50);
		slider.setMinorTickSpacing(10);
		
		c.add(slider);
		
		setSize(300, 100);
		setVisible(true);
	}
	

	public static void main(String[] args) {
		// Generated by SH Lee
		new SliderEx();
	}

}
