package java_Ch11_Swing;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

public class TextFieldEx extends JFrame {
	
	private Container c;
	
	public TextFieldEx() {
		setTitle("텍스트필드 예제");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		
		c = getContentPane();
		c.setLayout(new FlowLayout());
		
		c.add(new JLabel("이름"));
		c.add(new JTextField(20));
		c.add(new JLabel("학과"));
		c.add(new JTextField("컴퓨터공학과", 20));
		c.add(new JLabel("주소"));
		c.add(new JTextField("서울시 ...", 20));
		
		
		setSize(300, 150);
		setVisible(true);
	}

	public static void main(String[] args) {
		// Generated by SH Lee
		new TextFieldEx();
	}

}
