package java_Ch09_GUI;
import javax.swing.*;
import java.awt.*;

public class NullContainerEx extends JFrame {
	
	public NullContainerEx() {
		
		setTitle("Null Container Sample");
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);	// 종표버튼 클릭시 응용프로그램 종료

		Container c = getContentPane();
		c.setLayout(null);
		
		JLabel la = new JLabel("Hello Buttons!");
		la.setLocation(130, 50);
		la.setSize(200, 20);
		c.add(la);		// 라벨을 컨텐트패인에 부착
		
		for (int i=1; i<=9; i++) {
			JButton b = new JButton(Integer.toString(i));	// 버튼 생성
			b.setLocation(i*15, i*15);
			b.setSize(50, 20);
			c.add(b);	// 버튼을 컨텐트패인에 부착
		}
		
		setSize(300, 200);
		setVisible(true);
		
	}

	public static void main(String[] args) {
		// Generated by SH Lee
		
		new NullContainerEx();
	}

}
