package java_Ch05_Inheritance_Ex;

import java.util.Scanner;

public class Ex_09 {

	public static void main(String[] args) {
		// Generated by SH Lee

		Scanner scanner = new Scanner(System.in);
		
		System.out.print("총 스택 저장 공간의 크기 입력 >> ");
		int a = scanner.nextInt();
		
		StringStack stack = new StringStack(a);
		
		while (true) {
			
			System.out.print("문자열 입력 >> ");
			String str = scanner.next();
			
			if (str.equals("그만")) {
				scanner.close();
				break;
			}
			// 스택에 length()가 capacity()를 넘어가면 '불가' 출력
			else if (stack.length() > stack.capacity()) {
				System.out.println("스택이 꽉 차서 푸시 불가!");
			}
			else {
				stack.setContents(str);		// 스택에 문자열 쌓기(입력)
			}
		}
		System.out.print("스택에 저장된 모든 문자열 팝 : " );
		stack.printAll();
	}

}
