package java_Ch05_Inheritance_Ex;

public class Ex_01 {

	public static void main(String[] args) {
		// Generated by SH Lee
		
		ColorTV myTV = new ColorTV(32, 1024);
		myTV.printProperty();
		
	}

}
