package java_Ch05_Inheritance_Ex;

public class Ex_08 {

	public static void main(String[] args) {
		// Generated by SH Lee
		// 8. Point를 상속받아 양수의 공간에서만 점을 나타내는 PositivePoint 클래스를 작성하여라.​

		PositivePoint p = new PositivePoint();
		
		p.move(10, 10);
		System.out.println(p.toString()+ "입니다.");
		
		p.move(-5, 5);
		System.out.println(p.toString()+ "입니다.");
		
		PositivePoint p2 = new PositivePoint(-10, -10);
		System.out.println(p2.toString()+ "입니다.");
	}

}
