package java_Ch05_Inheritance_Ex;

public class Ex_03 {

	public static void main(String[] args) {
		// Generated by SH Lee
		// 연습문제 3
		
		Won2Dollar toDollar = new Won2Dollar(1200);
		toDollar.run();
	}

}
