package java_Ch05_Inheritance_Ex;

public class Ex_02 {

	public static void main(String[] args) {
		// Generated by SH Lee

		IPTV iptv = new IPTV("192.1.1.2", 32, 2048);
		iptv.printProperty();
		
	}

}
