package java_Ch05_Inheritance_Ex;

public class Ex_13 {

	public static void main(String[] args) {
		// Generated by SH Lee

		Shape donut = new Circle(10);	// 반지름이 10인 객체
		donut.redraw();
		System.out.println("면적은 " +donut.getArea());
	}

}
