package java_Ch05_Inheritance_Ex;

import java.util.Scanner;

public class Ex_11 {

	public static void main(String[] args) {
		// Generated by SH Lee

		Scanner scanner = new Scanner(System.in);
		System.out.print("두 정수와 연산자를 입력하시오>> ");
		
		int a = scanner.nextInt();
		int b = scanner.nextInt();
		char c = scanner.next().charAt(0);
		Calc calc;
		
		if (c=='+') {				// + 경우
			calc = new Add();
		}
		else if (c=='-') {			// - 경우
			calc = new Sub();
		}
		else if (c=='*') {			// * 경우
			calc = new Mul();
		}
		else if (c=='/') {			// / 경우
			calc = new Div();
		}
		else {
			System.out.println("연산자가 잘못되었습니다. 종료합니다.");
			scanner.close();
			return;
		}
		
		calc.setValue(a, b);
		System.out.println(calc.calculate());
		
		scanner.close();
	}

}
